version: '3.8'

services:
  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.deepseek.com/v1}
      - OPENAI_MODEL=${OPENAI_MODEL:-deepseek-chat}
      - QWEATHER_API_KEY=${QWEATHER_API_KEY}
      - QWEATHER_API_BASE=${QWEATHER_API_BASE:-https://api.qweather.com}
      - AMAP_API_KEY=${AMAP_API_KEY}
      - AMAP_BASE_URL=${AMAP_BASE_URL:-https://restapi.amap.com}
      - EXCHANGE_RATE_API_BASE=${EXCHANGE_RATE_API_BASE:-https://api.exchangerate.host}
      - EXCHANGE_RATE_API_KEY=${EXCHANGE_RATE_API_KEY}
    volumes:
      - ./results:/app/results
    networks:
      - travel-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端Streamlit服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - travel-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  travel-network:
    driver: bridge

volumes:
  results:
    driver: local
